title: oi
remote_theme: "jekyll/minima@1e8a445"

nav_pages:
  - about.md
  - teste.md
  - www.md
  - eee.md
  - fff.md
  - ggg.md
  - camisa.md
  - joao.md
  - carac.md
  - carac2.md
  - caraca.md
  - oi1.md
  - oi2.md
  - maria_zeferina.md

author:
  name: GitHub User
  email: your-email@domain.com
