title: oi
remote_theme: "jekyll/minima@1e8a445"

nav_bar:
  - about.md
  - teste.md
  - www.md
  - eee.md
  - fff.md
  - ggg.md
  - camisa.md
  - joao.md
  - carac.md
  - wande.md
  - dfdfdf.md
  - case.md

author:
  name: GitHub User
  email: your-email@domain.com
